### ISSUE TITLE
Compile error on Ubuntu and Amazon Linux

### ISSUE THREAD

**Issue by ronaldmannak** [dylanshine/openai-kit#1]
It looks like ByteBuffer isn't automatically bridged to Data on Linux, leading to the same compile error for every JSON decoding. 

[873](https://github.com/ronaldmannak/openai-kit/actions/runs/4152965648/jobs/7184288874#step:4:874)
`cannot convert value of type 'ByteBuffer' to expected argument type 'Data'
return try decoder.decode(T.self, from: byteBuffer)`

https://github.com/ronaldmannak/openai-kit/actions/runs/4152965648/jobs/7184288874#step:4:1033

**Comment by dylanshine** [comment]
Hey @ronaldmannak let me look into this. Which version of Swift are you compiling against?
