### ISSUE TITLE
Whisper API?

### ISSUE THREAD

**Issue by SebastianDanson** [dylanshine/openai-kit#13]
This isn't an issue, but will the Whisper API be added soon?

**Comment by dylanshine** [comment]
@SebastianDanson Can you provide a link to the documentation?

**Comment by jksk** [comment]
I think this is it. https://platform.openai.com/docs/guides/speech-to-text

**Comment by dylanshine** [comment]
I will start development of it over the weekend.

**Comment by dylanshine** [comment]
https://github.com/dylanshine/openai-kit/releases/tag/1.4.0
