### ISSUE TITLE
In Chat API, setting stream to true gives a different json structure

### ISSUE THREAD

**Issue by arthurgarzajr** [dylanshine/openai-kit#15]
When I implemented Chat, I didn't test what settings `stream` to true would do. Well, stream is very nice! But it returns data in a different way and this SDK currently doesn't support that.

**Comment by dylanshine** [comment]
@arthurgarzajr Can you provide an example of the response?

**Comment by jaysack** [comment]
I'm facing the same issue. I'm not sure what's the response type when setting `stream` to `true`, but here's an example from both response with Postman

Dropdown Opened | Dropdown Closed
--------------------- | ---------------------
<img src="https://user-images.githubusercontent.com/44855831/226170227-2b360372-7a3d-4050-b3dc-420c94cd8555.png" width="360"> | <img src="https://user-images.githubusercontent.com/44855831/226170232-8e1e6123-4f7e-4a51-9b7d-1b74ddb1a826.png" width="360">

**Comment by jaysack** [comment]
It looks like the `Content-Type` property changes to `text-event-stream` when `stream` is set to `true`. Do you guys know a way to receive this data type in Swift by any chance?

`stream` set to `true` | `stream` set to `false`
--------------------- | ---------------------
<img src="https://user-images.githubusercontent.com/44855831/226170599-2a6dbf70-5b5f-4e75-acc1-2452d7ea2e9f.png" width="360"> | <img src="https://user-images.githubusercontent.com/44855831/226170603-fd0b2566-a5f2-42bf-9661-eb3e8a0508df.png" width="360">

**Comment by dylanshine** [comment]
@jaysack I think we would need to add Event Source support to this framework in order to handle this use case. Would need to do more research before taking a stab at an implementation. Considering removing the stream parameter in the interim.

**Comment by cgaaf** [comment]
I've implemented streaming successfully using vanilla UrlSession async/await on a personal project. I've never contributed to open source before but I'd be happy to see if I can contribute.

**Comment by dylanshine** [comment]
@cgaaf More than happy for you to take a stab at it!

**Comment by dylanshine** [comment]
@ronaldmannak https://github.com/dylanshine/openai-kit/pull/36 adds stream support, curious if I could get your thoughts before merging

**Comment by ronaldmannak** [comment]
@dylanshine oh wow, with 19 changed files it looks like a bigger change than I thought. Let me use the branch and see how it works.

**Comment by dylanshine** [comment]
@ronaldmannak A lot of it was replacing `HTTPClient.Body` in favor of `Data` to be more flexible

**Comment by dylanshine** [comment]
PR merged...have fun
