### ISSUE TITLE
[Minor] Embedding Model is named with mismatching version

### ISSUE THREAD

**Issue by fjcaetano** [dylanshine/openai-kit#19]
The model `text-embedding-ada-002` is named as `case textEmbeddingAda001`. Shouldn't the suffix be Ada002?

Feel free to close this if there's a reason behind it that I'm missing. If this is actually issue, I'm more than happy to fix it.

https://github.com/dylanshine/openai-kit/blob/d93f61e19c1f57da2f781f19e137d4f8802b7037/Sources/OpenAIKit/Model/Model.swift#L46

**Comment by dylanshine** [comment]
Fixed :)
