### ISSUE TITLE
request handler error

### ISSUE THREAD

**Issue by halpz** [dylanshine/openai-kit#21]
It seems the response object is not mapping to the codable 'Completion' object properly:

I'm getting this error:

`keyNotFound(CodingKeys(stringValue: "id", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"id\", intValue: nil) (\"id\").", underlyingError: nil))`

**Comment by halpz** [comment]
maybe something has changed with the response object data structure?

**Comment by actow** [comment]
Getting the same error here.

**Comment by dylanshine** [comment]
So you're getting a response back without an ID I see...

**Comment by dylanshine** [comment]
Maybe something has changed, let me take a look...

**Comment by dylanshine** [comment]
@halpz Can you give me your input so I can try to reproduce?

**Comment by nathaniel11** [comment]
this is actually what happens when you are getting a error model returned. It tries to parse it into success model, fails and print the parsing error message.

**Comment by roddymunro** [comment]
Seeing the same issue - see my comment in the other issue: https://github.com/dylanshine/openai-kit/issues/22#issuecomment-1474626158

**Comment by dylanshine** [comment]
This is caused by a rogue print statement, will remove shortly.
