### ISSUE TITLE
crash on the Appdelegate 

### ISSUE THREAD

**Issue by Aaronwk** [dylanshine/openai-kit#3]
<img width="820" alt="image" src="https://user-images.githubusercontent.com/16297721/218698962-cbded3d3-c453-46ef-a0dc-4942c4d2d1e8.png">

<img width="883" alt="image" src="https://user-images.githubusercontent.com/16297721/218699080-d5b7c86a-5176-499b-bec4-0b4073f8dfb7.png">

**Comment by dylanshine** [comment]
Hey @Aaronwk, do you have a stack trace you could provide here? Could you also include an exception breakpoint in your next pass through?

**Comment by Aaronwk** [comment]
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/16297721/218915508-00c6ac80-5968-4a14-af6a-dd4d3ee26399.png">

**Comment by Aaronwk** [comment]
I'm sorry, it's my program itself. Thank you for your reply!。

**Comment by Aaronwk** [comment]
I'm sorry, it's my program itself. Thank you for your reply!
