### ISSUE TITLE
Example for usage of openai-kit

### ISSUE THREAD

**Issue by SaurabhPrajapati** [dylanshine/openai-kit#34]
@dylanshine This seems to be nice library for integration of OpenAI. I m here just suggesting if you can include Example of how to use this.  e.g. usage with env variables and usage without env variables and demonstrating usage of basic classes.

**Comment by dylanshine** [comment]
I think the difficulty with giving examples of injecting env variables is that there are so many different iOS and SSS frameworks to support. I would encourage consumers of this framework to research idiomatic patterns to handle env variables.

**Comment by SaurabhPrajapati** [comment]
This wasn't about just environment variables, actually it will be better to have some running example so users can download and run by just updating the API Key.

**Comment by dylanshine** [comment]
Literally what the test suite is used for.
