### ISSUE TITLE
revert-back-to-httpclient-dp

### ISSUE THREAD

**Issue by tharkhay4** [dylanshine/openai-kit#35]
revert-back-to-httpclient-dp

_Originally posted by @tharkhay4 in https://github.com/dylanshine/openai-kit/pull/33#pullrequestreview-1377458059_

**Comment by tharkhay4** [comment]
#30

**Comment by tharkhay4** [comment]
<details><summary>Details</summary>
<p>



</p>
</details>

**Comment by dylanshine** [comment]
@tharkhay4 What is this?
