### ISSUE TITLE
Stream fails the first time it's called

### ISSUE THREAD

**Issue by ronaldmannak** [dylanshine/openai-kit#40]
`Client.chats.stream()` fails the first time it's called. An empty stream is returned and the subsequent `for try await chat in stream { ... }` will never loop.

However, if `Client.chats.create()` is invoked *before* the first `Client.chats.stream()`, then the first `Client.chats.stream()` will succeed.

**Comment by dylanshine** [comment]
@ronaldmannak The unit test in the suite has never failed after the first call, curious what parameters you're passing in to reproduce this

**Comment by dylanshine** [comment]
https://github.com/dylanshine/openai-kit/pull/41
