### ISSUE TITLE
Crash in RequestHandler stream(request:)

### ISSUE THREAD

**Issue by JSky74** [dylanshine/openai-kit#43]
After cancelling a Task, this preconditionFailure is triggered:

preconditionFailure(
"Tried to use a second iterator on response body stream. Multiple iterators are not supported.",
file: file, line: line
)

Workaround is to only call `continuation.finish(throwing: error)` in the catch block of `stream(request:)` in RequestHandler and remove this:
` let data = try? await response.body.reduce(into: Data()) { $0.append(.init(buffer: $1)) }`

**Comment by dylanshine** [comment]
@JSky74 Do you want to make a PR with that change? I can here in a little in not

**Comment by JSky74** [comment]
@dylanshine Opened a PR.
