### ISSUE TITLE
WARNING: Hang Risk on setting up HTTP client

### ISSUE THREAD

**Issue by bluepixeltech** [dylanshine/openai-kit#44]
Hi, thanks for the good work on the library!

When I setup the http client as mentioned in your docs, i.e.:

let eventLoopGroup = MultiThreadedEventLoopGroup(numberOfThreads: 1)
let httpClient = HTTPClient(eventLoopGroupProvider: .shared(eventLoopGroup))

I receive the following warning:

**Hang Risk**
**Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_DEFAULT. Investigate ways to avoid priority inversions**

Any help on how to fix this would be appreciated!

**Comment by Madongming** [comment]
Same as my problem, waiting fixed.

**Comment by ftp27** [comment]
It won't be fixed. https://github.com/apple/swift-nio/issues/2223
You can try to init eventLoopGroup in another thread as mentioned in the issue above.
